version: "3.9"
name: static-demo

services:
  simple-static:
    image: nginx:alpine
    container_name: simple-static
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./static-site:/usr/share/nginx/html:ro
